kind: Service
apiVersion: v1
metadata:
  name: helloip-service
  labels:
    app: helloip
spec:
  selector:
    app: helloip
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
