apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: helloip-deployment
  labels:
    app: helloip
spec:
  replicas: 2
  strategy:
   type: Recreate
  selector:
    matchLabels:
      app: helloip
  template:
    metadata:
      labels:
        app: helloip
    spec:
      containers:
      - name: helloip
        image: gcr.io/drmtestproject-182723/helloip:v.02
        ports:
        - containerPort: 8080
